### ISSUE TITLE
RibbonView and Mainview interaction

### ISSUE THREAD

**Issue by jefjef** [WildGums/Orchestra#34]
I'm currently working on an modular Orchestra ribbon application
(using my own Syncfusion ribbon integration)

I fill the RibbonView And MainView like this in the OnInitialized method of the module: 

```C#
var serviceLocator = ServiceLocator.Default;
var ribbonService = serviceLocator.ResolveType<IRibbonService>();
var ribbon = ((RibbonView)ribbonService.GetRibbon()).Ribbon;
var mainView = ((MainView)ribbonService.GetMainView());

ribbon.Items.Add(TypeFactory.Default.CreateInstance<ModuleARibbonView>());
mainView.GroupBar.Items.Add(TypeFactory.Default.CreateInstance<ModuleAGroupBarView>());
mainView.ContentControl.Content = TypeFactory.Default.CreateInstance<ProductSearchView>();
```

I moved the MainView, RibbonView And StatusBarView from my shell to a contract library so modules can interact with it.

ModuleARibbonView, ModuleAGroupBarView and ProductSearchView are custom controls
that fill the Ribbon and MainView with controls
(i'll probably have to implement IUserControl in them, but for now I'm setting the datacontext manually)

This is how it currently looks, so you have an idea:

![2015-07-14_15-08-35](https://cloud.githubusercontent.com/assets/254635/8673848/40d4eafa-2a3a-11e5-900e-e4560bbd1643.png)

The question i have now:
How can i make my 3 views interact with each other? 
For example:
* Refresh the list when the refresh button in the Ribbon gets clicked 
(im currently using an application wide command for this, doesnt feel ike the correct solution)
* Fill in the textbox in the ribbon when an item gets selected
* Filter the list when an item gets selected 

I could make an ViewModel that gets used by multiple Views 
(its stated in https://catelproject.atlassian.net/wiki/display/CTL/Finding+the+view+of+a+view+model that this is possible, but i cant find any more documentation on this) 

How do you propose i continue?

**Comment by GeertvanHorrik** [comment]
Good question. I prefer communications to take place in services. Services are long living (registered inside the ServiceLocator) objects that will be available to any object inside an application. Therefore they are a great way to manage state, etc.

View models contain logic bound to a specific view. This view may or may not be alive, so we can't put (state) management in there. 

Re-using view models is a very bad idea, but that's what most people do. This is how we solve this issue (successfully) in all our apps:

1. For commands, use [command containers](https://catelproject.atlassian.net/wiki/pages/viewpage.action?pageId=18972710#CommandManagerandcommandcontainers(Application-widecommands)-Commandcontainers|command containers). Commands are mostly application-wide, and should be executable even when a view / view model is not alive. For example, a refresh command is something that should work, even when one of the views that can be refreshed is not alive. Note that even when you use command containers, you can add / remove per view model implementation for that same command. It might be a bit hard to get your head around it, but once you understand you don't want to go back to regular commands.

2. For state, use services. This means that if you need to manage data, you will have an IDataManagementService. This service will be registered inside the ServiceLocator (and might even be defined in a contract assembly). Then even plugins can interact (but don't have to be aware of the implementation). Then if a vm needs to interact with the data, they inject the service into the constructor. Since the services have events, view models (that are alive) can respond to it. If your vm is not alive, you don't have to respond to it.

If I remember correctly, the examples inside Orchestra have command containers (at least the Fluent ribbon example). We have 1 open source app that we built on Orchestra that you might want to take a look at. We haven't converted that one to application commands, etc yet, but it might give you a clue on how to interact with services. You can find it [here](https://github.com/WildGums/LogViewer).

**Comment by jefjef** [comment]
Alright i can probably continue from here, thanks.
You can close the issue, i'll update if i have any more questions
